### PR TITLE
Setup Github Actions Workflow

### PR DESCRIPTION
**Pull request by cs-uche**
- Created workflow to publish docker image
- Updated workflow to automatically add image tag to docker compose file

### CODE REVIEW

**Comment by cs-uche** [comment]
Please view the Pull Request associated with this issue #28.

**Comment by cs-uche** [comment]
The current setup will only be triggered on updates to the `Dockerfile`  or `conda-linux-64.lock` files on the associated branch `workflow-setup`

**Comment by cs-uche** [comment]
The current setup successfully pushes the docker image to Docker Hub(image attached below)
image

**Comment by cs-uche** [comment]
- docker compose tested locally(image attached below)
image
image

**Comment by AzinPiran** [comment]
Thanks for adding the action and changing the Docker file to trigger the workflow.

**Pull request merged**
