### PR TITLE
Modularizing the notebook into scripts

### PR DESCRIPTION
**Pull request by cs-uche**
- [x] Validations script
- [x] Pre-processing script
- [x] EDA script
- [x] Modelling and evaluation script

### CODE REVIEW

**Comment by cs-uche** [comment]
Please do not merge this PR till all the scripts have been checked off and you have tested the commands to run them

**Comment by cs-uche** [comment]
The commands will be moved to the README once they are finalized

**Comment by HrayrMuradyan** [comment]
Hey guys, I added the eda.py file. Tomorrow morning will finalize the scripts and we can review it and merge.

**Comment by HrayrMuradyan** [comment]
Firstly, thanks @cs-uche for doing a great job on the evaluation and training files! Here are the changes I made, please review it and tell me if you disagree:

1. I changed the underscore (_) to dash (-) in the arguments to be consistent throughout the scripts (i.e. --path_to -> --path-to).
2. In the **model_training.py** file here are the changes I made:
- Changed the evaluation metric so that it is passed by the user as a separate argument (--eval-metric) which can be either an accuracy, recall, precision or f1.
- Changed the number of hyperparameters to check
- Changed the number of cross-validation to do (to have more cv samples)
- Added a plot that plots parameters vs. validation and train scores, which shows how the score changes. The plot is saved in the /results/figures/ folder.
- Additionally, I save the cross validation results in a separate table.
3. From the **model_evaluation.py** file I removed ROC, AP, PR curves. For now lets move on without them, we can add it later if we find out that we actually need them.

Throughout all the scripts I am using Path class from pathlib module and it is widely used nowadays in machine learning, which is compatible with different operating systems. I used that module to do all path-related operations in the scripts. 

Please review it and let me know if you want to suggest alternatives. Also, please note that I haven't fully finalized them yet. I will make it more consistent and better documented soon.

**Comment by cs-uche** [comment]
okay @HrayrMuradyan

**Comment by AzinPiran** [comment]
Hi everyone, you used these modules in the scripts, 
`kagglehub`, `click`, `deepchecks` 
Please also add them to the .yml file. and update the conda lock file and make sure the Docker compose file is working.

**Comment by cs-uche** [comment]
> Hi everyone, you used these modules in the scripts, `kagglehub`, `click`, `deepchecks` Please also add them to the .yml file. and update the conda lock file and make sure the Docker compose file is working.

Hey @AzinPiran the environment file has been updated an image rebuilt and docker compose executes successfully see reference image below
terminal docker compose

hosted jupyter lab

**Comment by cs-uche** [comment]
But the deepcheks version does not include the required functions for this analysis, I am currently working on updating the environment.

**Comment by cs-uche** [comment]
All tests passed, View the image below for the result from running the commands in the README from within the container

image

**Pull request merged**
